export interface PDFTool {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: 'core' | 'management' | 'to-pdf' | 'from-pdf' | 'ai' | 'utility';
}

export const PDF_TOOLS: PDFTool[] = [
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one document.',
    icon: 'Merge',
    category: 'core',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion.',
    icon: 'Scissors',
    category: 'core',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce the file size of your PDF while optimizing for maximal PDF quality.',
    icon: 'Minimize2',
    category: 'core',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF to editable Word documents.',
    icon: 'FileText',
    category: 'core',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF.',
    icon: 'FileCode',
    category: 'core',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Extract all images from a PDF or convert each page to a JPG image.',
    icon: 'Image',
    category: 'core',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG, PNG, BMP, GIF, and TIFF images to PDF.',
    icon: 'FileImage',
    category: 'core',
  },
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, images, shapes or freehand annotations to a PDF.',
    icon: 'Edit3',
    category: 'management',
  },
  {
    id: 'chat-with-pdf',
    name: 'Chat with PDF',
    description: 'Use AI to summarize, translate, and answer questions about your PDF.',
    icon: 'MessageSquare',
    category: 'ai',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once!',
    icon: 'RotateCw',
    category: 'management',
  },
  {
    id: 'delete-pages',
    name: 'Delete Pages',
    description: 'Remove pages from your PDF document.',
    icon: 'Trash2',
    category: 'management',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt your PDF with a password to prevent unauthorized access.',
    icon: 'Lock',
    category: 'core',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password from PDF files.',
    icon: 'Unlock',
    category: 'core',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert PDF tables to Excel spreadsheets.',
    icon: 'Table',
    category: 'from-pdf',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF.',
    icon: 'FileSpreadsheet',
    category: 'to-pdf',
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PPT',
    description: 'Convert PDF to PowerPoint presentations.',
    icon: 'Presentation',
    category: 'from-pdf',
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark',
    description: 'Add text or image watermark to your PDF.',
    icon: 'Stamp',
    category: 'management',
  },
  {
    id: 'pdf-ocr',
    name: 'PDF OCR',
    description: 'Recognize text in scanned PDFs.',
    icon: 'ScanText',
    category: 'ai',
  },
  {
    id: 'rearrange-pages',
    name: 'Rearrange Pages',
    description: 'Change the order of pages in your PDF.',
    icon: 'Layers',
    category: 'management',
  },
  {
    id: 'edit-metadata',
    name: 'Edit Metadata',
    description: 'Change PDF title, author, subject, and keywords.',
    icon: 'Settings2',
    category: 'management',
  },
  {
    id: 'extract-images',
    name: 'Extract Images',
    description: 'Extract all images from a PDF file.',
    icon: 'Images',
    category: 'management',
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    description: 'Convert PDF pages to PNG images.',
    icon: 'FileImage',
    category: 'from-pdf',
  },
  {
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    description: 'Convert PNG images to PDF.',
    icon: 'ImagePlus',
    category: 'to-pdf',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert web pages or HTML files to PDF.',
    icon: 'Globe',
    category: 'to-pdf',
  },
  {
    id: 'txt-to-pdf',
    name: 'TXT to PDF',
    description: 'Convert text files to PDF.',
    icon: 'FileText',
    category: 'to-pdf',
  },
  {
    id: 'pdf-summarizer',
    name: 'PDF Summarizer',
    description: 'Get a quick summary of your PDF using AI.',
    icon: 'FileSearch',
    category: 'ai',
  },
  {
    id: 'pdf-translator',
    name: 'PDF Translator',
    description: 'Translate your PDF to any language using AI.',
    icon: 'Languages',
    category: 'ai',
  },
];
